# Generated by Django 3.2.8 on 2021-10-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Briefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.CharField(max_length=200, verbose_name='E-mail')),
                ('company', models.CharField(max_length=100, verbose_name='Empresa')),
                ('prgum', models.TextField(blank=True, max_length=200, null=True, verbose_name='1. Qual é o nicho de atuação da sua empresa?')),
                ('prgdois', models.TextField(max_length=80, verbose_name='2. A quanto tempo sua empresa está no mercado? ')),
                ('prgtres', models.TextField(max_length=200, verbose_name='3. Conte um pouco sobre a sua empresa:')),
                ('prgquatro', models.TextField(max_length=200, verbose_name='4. Quais produtos e ou serviços sua empresa oferece?')),
                ('prgcinco', models.TextField(max_length=1, verbose_name='5. Conte um pouco sobre seu público-alvo:')),
                ('prgseisa', models.BooleanField(blank=True, null=True, verbose_name='A')),
                ('prgseisb', models.BooleanField(blank=True, null=True, verbose_name='B')),
                ('prgseisc', models.BooleanField(blank=True, null=True, verbose_name='C')),
                ('prgseisd', models.BooleanField(blank=True, null=True, verbose_name='D')),
                ('prgseisout', models.CharField(blank=True, max_length=100, null=True, verbose_name='Outros')),
                ('prgsete1', models.CharField(blank=True, max_length=100, null=True, verbose_name='1º Concorrênte')),
                ('prgsete2', models.CharField(blank=True, max_length=100, null=True, verbose_name='2º Concorrênte')),
                ('prgsete3', models.CharField(blank=True, max_length=100, null=True, verbose_name='3º Concorrênte')),
                ('prgoito', models.TextField(blank=True, max_length=300, null=True, verbose_name='8. Qual mensagem você quer passar para o público?')),
                ('prgnove1', models.TextField(max_length=50, verbose_name='1. Possui alguma preferência de cores? Se sim, quais?')),
                ('prgnove2', models.TextField(max_length=50, verbose_name='2. Existe alguma cor que você não queira? Se sim, quais?')),
                ('prgdez', models.TextField(blank=True, max_length=100, null=True, verbose_name='10. Possui slogan? Se sim, qual?')),
                ('prgonze', models.TextField(blank=True, max_length=100, null=True, verbose_name='11. Existe alguma outra marca/empresa que te inspira?')),
                ('prgdoze1', models.BooleanField(blank=True, null=True, verbose_name='Moderna')),
                ('prgdoze2', models.BooleanField(blank=True, null=True, verbose_name='Séria')),
                ('prgdoze3', models.BooleanField(blank=True, null=True, verbose_name='Extrovertida')),
                ('prgdoze4', models.BooleanField(blank=True, null=True, verbose_name='Delicada')),
                ('prgdoze5', models.BooleanField(blank=True, null=True, verbose_name='Conservadora')),
                ('prgdoze6', models.BooleanField(blank=True, null=True, verbose_name='Divertida')),
                ('prgdoze7', models.BooleanField(blank=True, null=True, verbose_name='Elegante')),
                ('prgdoze8', models.BooleanField(blank=True, null=True, verbose_name='Nerd/Geek')),
                ('prgtreze1', models.BooleanField(blank=True, null=True, verbose_name='SIM')),
                ('prgtreze2', models.BooleanField(blank=True, null=True, verbose_name='NÃO')),
                ('prgquatorze1', models.BooleanField(blank=True, null=True, verbose_name='Cartão de visita')),
                ('prgquatorze2', models.BooleanField(blank=True, null=True, verbose_name='Papel Timbrado')),
                ('prgquatorze3', models.BooleanField(blank=True, null=True, verbose_name='Assinatura de e-mail')),
                ('prgquatorze4', models.BooleanField(blank=True, null=True, verbose_name='Envelope saco (A4)')),
                ('prgquatorze5', models.BooleanField(blank=True, null=True, verbose_name='Envelope Carta')),
                ('prgquatorze6', models.BooleanField(blank=True, null=True, verbose_name='Pasta')),
                ('prgquatorze7', models.BooleanField(blank=True, null=True, verbose_name='Crachá')),
                ('prgquatorze8', models.TextField(blank=True, max_length=100, null=True, verbose_name='outros')),
                ('prgfinal', models.TextField(blank=True, max_length=300, null=True, verbose_name='Você tem algo a mais para relatar?')),
            ],
        ),
    ]
