# Generated by Django 3.2.8 on 2021-10-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vortex_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='briefing',
            name='prgcinco',
            field=models.TextField(max_length=200, verbose_name='5. Conte um pouco sobre seu público-alvo:'),
        ),
    ]
